// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcqrdimdzuzpqbfzkzrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjcXJkaW1kenV6cHFiZnprenJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODg1NTksImV4cCI6MjA2Mzc2NDU1OX0.RfZaPaEBeBLhOFq9UVgxuA9GcKEPTBG-lU8-YFgbo9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);